config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  
  root 'users#new'
  get '/log_out', to: 'users#log_out'
  get '/admin_new', to: 'admin#admin_new'
  post '/admin_create', to: 'admin#admin_create'
  post '/index_json', to: 'leaderboards#index_json'
  post '/show_json', to: 'leaderboards#show_json' 

  post '/scores/new_from_endpoint' => 'scores#new_from_endpoint'

  get '/scores/admin_new' => 'scores#admin_new'
  post '/scores/set' => 'scores#admin_create'

  resources :scores
  resources :leaderboards

  get '/admin' => 'admin#index'

  get 'playground/index' => 'playground#index'


  get '/pdf' => 'admin#pdfs'

  # root 'playground#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
require 'csv'    

class User < ApplicationRecord
  has_many :scores, dependent: :destroy

  validates :username, presence: true

  validates_format_of :username, :with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/

  def create_scores
    games = Game.all
    games.each do |game|
      s = Score.new
      s.game_id = game.id
      s.user_id = self.id
      s.points = 0
      s.save
    end

  end

  def self.total_districts
    total_districts = User.all.group_by(&:district_name).keys
    total_districts.reject {|district| district == "" || district == nil}.sort
  end
  # => ["", "West District", "East District", "Central District", "Boston, MA", ...]

  def self.overall_count_of_districts
    User.total_districts.map do |district_name|
      {district: district_name, num_of_people: User.all.where("district_name = ?", district_name).where("district_name != 'Home Office'").where("district_name != 'Medical'").where("district_name != ''").where("district_name != 'Dome'").count }
    end.sort_by {|obj| obj[:num_of_people] }.reverse
  end
  # => [{:district=>"", :num_of_people=>121}, {:district=>"New York, NY", :num_of_people=>27}, ...]

  def self.find_users_per_district(district_name)
    User.all.group_by(&:district_name)[district_name]
  end
  # => #<User id: 111, created_at: "2016-09-19 20:52:49", updated_at: "2016-09-19 20:52:49" ...]

  def self.get_user_ids_per_district(district_name)
    User.find_users_per_district(district_name).map {|obj| obj[:id]}
  end

  def self.get_scores_per_district(district_name)
    scores_hash = {district_name: district_name, score: score_array = []}
    User.get_user_ids_per_district(district_name).each do |user_id|
      # {district_name: district_name, score: Score.find_by(user_id: user_id).points}
      # {district_name: district_name, score: score_array << Score.find_by(user_id: user_id).points }
      if !Score.find_by(user_id: user_id).nil?
        score_array << Score.find_by(user_id: user_id).points
      end
    end
    scores_hash[:score] = scores_hash[:score].sum
    scores_hash
  end

  def self.get_scores_for_all_districts
    district_scores_array = []
    all_districts = User.total_districts
    all_districts.each do |district|
      district_scores_array << User.get_scores_per_district(district)
    end
    district_scores_array.sort_by {|obj| obj[:score]}.reverse
  end

  def self.ruby_final_score
    return_array = []
    sql = "SELECT DISTINCT district_name, 
    COALESCE((
     SELECT (
       SUM(scores.points)
    ) 
    FROM users 
    JOIN scores on scores.user_id = users.id 
    WHERE users.district_name = u.district_name
    ), 0) 
    AS score FROM users AS u 
    WHERE district_name != ''
    AND district_name != 'Home Office'
    AND district_name != 'Medical'
    AND district_name != 'Dome'
    ORDER BY score DESC"
    records_array = ActiveRecord::Base.connection.select_all(sql)
    highest_num_in_district = User.overall_count_of_districts[0][:num_of_people]
    records_array.map do |record|
       weighted = highest_num_in_district / User.get_user_ids_per_district(record["district_name"]).count.to_f
       record["score"] = (record["score"] * weighted).round
       record
    end.sort_by {|obj| obj["score"]}.reverse
  end

  def self.sql_final_score
  sql = "SELECT DISTINCT district_name,
  COALESCE((
    SELECT ( 
      CEILING (
        SUM(scores.points) * (
           SELECT MAX(
                   (SELECT COUNT(id)
                    FROM users
                    WHERE district_name = u.district_name)
          ) num_of_users
              FROM users AS u
              WHERE district_name != ''
              AND district_name != 'Home Office'
              AND district_name != 'Medical'
              AND district_name != 'Dome'
        ) / (
          SELECT COUNT(id)
              FROM users
              WHERE users.district_name = u.district_name
        )
      )
    )
     FROM users
     JOIN scores ON scores.user_id = users.id
     WHERE users.district_name = u.district_name 
  ),0)
  AS score 
  FROM users AS u
  WHERE district_name != ''
  AND district_name != 'Home Office'
  AND district_name != 'Medical'
  AND district_name != 'Dome'  
  ORDER BY score DESC"
  records_array = ActiveRecord::Base.connection.select_all(sql)
  end


# User.social_media_sheet('csv-example1.csv', 1)
  def self.social_media_sheet(csv_file_name, game_id)
    csv_text = File.read('CSV/' + csv_file_name)
    # csv = CSV.parse(csv_text, :headers => true)
    csv = CSV.parse(csv_text)
    total_points = 0
    csv.each_with_index do |row, index|
      cur = csv[index][0]
      user = User.find_by(username: cur)
      if user
        if csv.length - 1  == index
          #last row so just put total in the db
          total_points += csv[index][-1].to_i
          Score.create(user_id: user.id , game_id: game_id, points: total_points)
        else  
          next_m = csv[index+1][0]
          total_points += csv[index][-1].to_i
          if cur != next_m
          Score.create(user_id: user.id , game_id: game_id, points: total_points)
          total_points = 0
          end 
        end
      end
    end
  end

  def self.find_lcm
    # Make sure 0 is not included in the array
    User.overall_count_of_districts.map do |obj|
      obj[:num_of_people]
    end.uniq.reduce(:lcm)
  end
  #  => 1367566200 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
layout 'login'

  def index
    redirect_to root_path
  end

  def new
    @user = User.new
    if cookies[:username]
      if @user = User.find_by(username: cookies[:username])
        redirect_to @user
      else
        # If the cookie exists but not the associated user,
        # remove the cookies to avoid a feedback loop
        remove_cookies
        redirect_to root_path
      end
    end
  end

  def create
    username = params["user"]["username"]
    if @user = User.where('lower(username) = lower(?)', username)[0]
      set_cookies(@user)
      redirect_to @user
    else
      flash[:notice] = "User doesn't exist"
      redirect_to root_path
    end
  end



  # def create
  #   if @user = User.find_by(username: params['user']['username'])
  #     set_cookies(@user)
  #     redirect_to @user
  #   else
  #     @user = User.new(user_params)
  #     @user.save
  #     render 'new'
  #   end
  # end


  # def create
  #   if @user = User.find_by(username: params['user']['username'])
  #     set_cookies(@user)
  #     redirect_to @user
  #   else
  #     @user = User.new(user_params)
  #     if @user.save
  #       set_cookies(@user)
  #       redirect_to @user
  #     else
  #       render 'new'
  #     end
  #   end
  # end

  def show
    @user = User.find(params[:id])
    redirect_to '/playground/index'
  end

  def log_out
    remove_cookies
    redirect_to root_path
  end

  def destroy
    @user = User.find(params[:id])
    # If you're deleting the currently logged-in user, delete the cookies as well
    remove_cookies if cookies[:username] == @user.username
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_path, notice: 'User was successfully removed.' }
      format.json { head :no_content }
    end
  end


  private

    def user_params
      @task = params[:user].permit(:username)
    end

    def remove_cookies
      cookies.delete(:username)
      cookies.delete(:user_id)
    end

    def set_cookies(user)
      cookies[:username] = user.username
      cookies[:user_id] = user.id
    end

end


app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/admin_new.html.erb


<%= form_for @user, :url => url_for(:controller => 'users', :action => 'admin_create') do |f| %>
  <%= render 'shared/error_messages' %>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>

  <div class="actions">
    <%= f.submit "Create User" %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: "flash" %>
<% end -%>

<div class="all-users">

<% @users.each do |user| %>
  <div class="user-info">

    <div class="admin-label">
    Username:
    </div>

    <div class="admin-details">
    <span class="username">
      <%= link_to(user.username, user_path(user)) %> 
    </span>
    <%= link_to 'Delete User', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "little-link" %>
    </div><br/>

    <% if user.scores.length > 0 %>
      <div class="admin-label">
      Scores:
      </div>

      <div class="admin-details">
        <% user.scores.each do |score| %>
          Game: <%= score.get_game_name %> / Score: <%= score.points %>
          <%= link_to("Edit", edit_score_path(score), :class => "little-link") %>
          <%= link_to 'Delete', score, method: :delete, data: { confirm: 'Are you sure?' }, class: "little-link" %><br/>
        <% end %>
      </div>
    <% end %>

    <div class="add-score">
      <%= link_to "Add a new score", {:controller => "scores", :action => "new", :user_id => user.id }%>
    </div>

  </div>

<% end %>

</div>

<div class="add-user">
  <%= link_to "Add a new user", admin_new_path %>
</div>

app/views/users/new.html.erb

<div class="container">
  <div class="close"></div>
  <div class="container-table">
    <div class="container-cell">
      <div class="page-heading">
        <%= image_tag('sb.png') %>
      </div>
      <div class="signin">
        <%= form_for(@user) do |f| %>
          <%= render 'shared/error_messages' %>
          <div class="field">
            <%= f.label :username, "Welcome to the Strong Breakthrough Competition. Enter you Janssen email address below to access the room." %><br>
            <% flash.each do |name, msg| -%>
              <%= content_tag :div, msg, class: "flash" %>
            <% end -%>
            <%= f.text_field :username, placeholder: "Email Address" %>
          </div>

          <div class="actions">
            <%= f.submit "BEGIN", class: "s-btn" %>
          </div>
        <% end %>  

      </div>  
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.username %>'s Profile</h1>

<div class="scores">
Scores:<br/>
<% @user.scores.each do |score| %>
  Game: <%= score.get_game_name %> / Score: <%= score.points %><br/>
<% end %>
</div>

<div class="start-over">
Not <%= @user.username %>? 
<%= link_to("Start Over", log_out_path) %>
</div>